# Generated by Django 5.1.1 on 2024-09-04 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='firsts/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ER', 'EARINGS'), ('NL', 'NECKLACE'), ('RG', 'RINGS'), ('NS', 'NOSEPINS'), ('TP', 'TOPS')], max_length=2)),
            ],
        ),
    ]
