# Generated by Django 5.1.1 on 2024-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
